import 'package:flutter_test/flutter_test.dart';
import 'package:fuckcorpo/features/achievements/earnings_statement.dart';

String _usd(num amount) => '\$${amount.toStringAsFixed(2)}';

void main() {
  group('A3 clipboard payload', () {
    test('matches the React ASCII statement line for line', () {
      final String text = buildEarningsStatement(
        lifetimeEarned: 1234.5,
        totalSessions: 42,
        totalDurationMs: 3 * 3600000 + 25 * 60000 + 7 * 1000,
        avgDurationMs: 4 * 60000 + 53 * 1000,
        mostCommonCategory: 'Bathroom',
        unlockedCount: 6,
        totalAchievements: 11,
        date: DateTime(2026, 7, 28),
        formatMoney: _usd,
      );

      expect(text, <String>[
        '========================================',
        '   OFFICIAL EARNINGS STATEMENT',
        '   FuckCorpo Inc.',
        '   Date: July 28, 2026',
        '========================================',
        '',
        r'   Lifetime Earnings: $1234.50',
        '   Total Sessions: 42',
        '   Total Time Invested: 03:25:07',
        '   Average Session: 04:53',
        '   Primary Category: Bathroom',
        '   Achievements Unlocked: 6/11',
        '',
        '   BOARD OF DIRECTORS: YOU',
        '',
        '   --- CONFIDENTIAL ---',
        '   Generated by FuckCorpo Inc.',
        '========================================',
      ].join('\n'));
    });

    test('the statement date is rendered in the long en-US form', () {
      expect(statementDate(DateTime(2026, 1, 5)), 'January 5, 2026');
      expect(statementDate(DateTime(2026, 12, 31)), 'December 31, 2026');
    });
  });

  group('A4 CEO comparison', () {
    test('the CEO rate is the React constant', () {
      expect(ceoRatePerMinute, 83.33);
    });

    test('CEO earnings scale with the total time invested', () {
      // 60 minutes of breaks.
      expect(ceoEarningsFor(60 * 60000), closeTo(4999.8, 0.0001));
    });

    test('the multiplier rounds to a whole number', () {
      expect(ceoMultiplier(ceoEarnings: 4999.8, lifetimeEarned: 60), '83');
    });

    test('zero lifetime earnings yields a zero multiplier, not a divide', () {
      expect(ceoMultiplier(ceoEarnings: 100, lifetimeEarned: 0), '0');
    });
  });
}
