import { useState, useEffect, useMemo, useRef } from 'react';
import { useApp } from '../context/AppContext';
import { useToast } from '../context/ToastContext';
import useSound from '../hooks/useSound';
import { formatCurrency, totalEarnings, totalDuration, formatDuration, calculateEarnings } from '../utils/calculations';
import Card from '../components/shared/Card';
import Button from '../components/shared/Button';
import PageTransition from '../components/shared/PageTransition';
import './Achievements.css';

const ACHIEVEMENTS = [
  { id: 'first_flush', name: 'First Flush', desc: 'Log your first break', icon: '🚽', check: (breaks) => breaks.length >= 1 },
  { id: 'regular', name: 'The Regular', desc: 'Log 10 breaks', icon: '📊', check: (breaks) => breaks.length >= 10 },
  { id: 'consistency', name: 'Consistency Champion', desc: 'Log 50 breaks', icon: '🏆', check: (breaks) => breaks.length >= 50 },
  { id: 'century', name: 'Century', desc: 'Log 100 breaks', icon: '💯', check: (breaks) => breaks.length >= 100 },
  { id: 'hundred_club', name: '$100 Club', desc: 'Earn $100 lifetime', icon: '💵', check: (breaks, earned) => earned >= 100 },
  { id: 'thousand_club', name: '$1,000 Club', desc: 'Earn $1,000 lifetime', icon: '💰', check: (breaks, earned) => earned >= 1000 },
  { id: 'ten_k_club', name: '$10,000 Club', desc: 'Earn $10,000 lifetime', icon: '🏦', check: (breaks, earned) => earned >= 10000 },
  { id: 'marathon', name: 'Marathon Runner', desc: 'Single session over 30 min', icon: '🏃', check: (breaks) => breaks.some(b => b.duration >= 30 * 60000) },
  { id: 'quick_draw', name: 'Quick Draw', desc: 'Session under 2 minutes', icon: '⚡', check: (breaks) => breaks.some(b => b.duration > 0 && b.duration <= 2 * 60000) },
  { id: 'early_bird', name: 'Early Bird', desc: 'Break before 9 AM', icon: '🌅', check: (breaks) => breaks.some(b => new Date(b.timestamp).getHours() < 9) },
  { id: 'night_owl', name: 'Night Owl', desc: 'Break after 6 PM', icon: '🦉', check: (breaks) => breaks.some(b => new Date(b.timestamp).getHours() >= 18) },
];

const CEO_RATE_PER_MINUTE = 83.33;

export default function Achievements() {
  const { state, dispatch, perMinuteRate } = useApp();
  const { addToast } = useToast();
  const { achievementSound } = useSound();
  const { breaks, achievements } = state;
  const [copied, setCopied] = useState(false);
  const toastedRef = useRef(new Set(achievements));

  const lifetimeEarned = useMemo(() => totalEarnings(breaks, perMinuteRate), [breaks, perMinuteRate]);
  const lifetimeDuration = useMemo(() => totalDuration(breaks), [breaks]);

  // Check and dispatch newly unlocked achievements
  useEffect(() => {
    ACHIEVEMENTS.forEach((a) => {
      if (!achievements.includes(a.id) && a.check(breaks, lifetimeEarned)) {
        dispatch({ type: 'ADD_ACHIEVEMENT', payload: a.id });
        if (!toastedRef.current.has(a.id)) {
          toastedRef.current.add(a.id);
          addToast(`Achievement Unlocked: ${a.name}!`, 'achievement');
          achievementSound();
        }
      }
    });
  }, [breaks, lifetimeEarned, achievements, dispatch, addToast, achievementSound]);

  const unlockedCount = ACHIEVEMENTS.filter(a => achievements.includes(a.id)).length;

  // Stats for the earnings statement
  const avgDuration = breaks.length > 0 ? lifetimeDuration / breaks.length : 0;
  const categoryCount = {};
  breaks.forEach(b => {
    const cat = b.category || 'Uncategorized';
    categoryCount[cat] = (categoryCount[cat] || 0) + 1;
  });
  const mostCommonCategory = Object.entries(categoryCount).sort((a, b) => b[1] - a[1])[0]?.[0] || 'N/A';

  // CEO comparison
  const totalMinutes = lifetimeDuration / 60000;
  const ceoEarnings = totalMinutes * CEO_RATE_PER_MINUTE;
  const multiplier = lifetimeEarned > 0 ? (ceoEarnings / lifetimeEarned).toFixed(0) : 0;

  function handleCopyStatement() {
    const text = [
      '========================================',
      '   OFFICIAL EARNINGS STATEMENT',
      '   FuckCorpo Inc.',
      `   Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
      '========================================',
      '',
      `   Lifetime Earnings: ${formatCurrency(lifetimeEarned)}`,
      `   Total Sessions: ${breaks.length}`,
      `   Total Time Invested: ${formatDuration(lifetimeDuration)}`,
      `   Average Session: ${formatDuration(avgDuration)}`,
      `   Primary Category: ${mostCommonCategory}`,
      `   Achievements Unlocked: ${unlockedCount}/${ACHIEVEMENTS.length}`,
      '',
      '   BOARD OF DIRECTORS: YOU',
      '',
      '   --- CONFIDENTIAL ---',
      '   Generated by FuckCorpo Inc.',
      '========================================',
    ].join('\n');

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <PageTransition className="achievements-page container">
      {/* Page Header */}
      <header className="achievements-header">
        <h2>INVESTOR ACHIEVEMENTS</h2>
        <p className="achievements-subtitle">Your portfolio of bathroom accomplishments</p>
        <p className="achievements-progress mono">
          <span className="text-gold">{unlockedCount}</span>
          <span className="text-gray"> / {ACHIEVEMENTS.length} unlocked</span>
        </p>
      </header>

      {/* Achievement Badges Grid */}
      <section className="achievements-grid">
        {ACHIEVEMENTS.map((a) => {
          const unlocked = achievements.includes(a.id);
          return (
            <Card key={a.id} className={`achievement-card ${unlocked ? 'achievement-unlocked' : 'achievement-locked'}`}>
              <div className={`achievement-badge ${unlocked ? 'badge-unlocked' : 'badge-locked'}`}>
                {unlocked ? (
                  <span className="badge-icon">{a.icon}</span>
                ) : (
                  <span className="badge-icon badge-lock">🔒</span>
                )}
              </div>
              <h4 className="achievement-name">{a.name}</h4>
              <p className="achievement-desc">{a.desc}</p>
              {unlocked && <span className="achievement-status text-green mono">UNLOCKED</span>}
              {!unlocked && <span className="achievement-status text-gray mono">LOCKED</span>}
            </Card>
          );
        })}
      </section>

      {/* Shareable Earnings Statement */}
      <section className="earnings-statement-section">
        <Card elevated className="earnings-statement">
          <div className="statement-watermark">CONFIDENTIAL</div>
          <div className="statement-content">
            <h3 className="statement-title">OFFICIAL EARNINGS STATEMENT</h3>
            <p className="statement-company">FuckCorpo Inc.</p>
            <p className="statement-date text-gray">
              {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>

            <div className="statement-divider" />

            <div className="statement-hero-number">
              <span className="statement-label">Lifetime Earnings</span>
              <span className="statement-amount text-green mono">{formatCurrency(lifetimeEarned)}</span>
            </div>

            <div className="statement-divider" />

            <div className="statement-stats">
              <div className="statement-stat">
                <span className="statement-stat-label">Total Sessions</span>
                <span className="statement-stat-value mono">{breaks.length}</span>
              </div>
              <div className="statement-stat">
                <span className="statement-stat-label">Average Duration</span>
                <span className="statement-stat-value mono">{formatDuration(avgDuration)}</span>
              </div>
              <div className="statement-stat">
                <span className="statement-stat-label">Most Common Category</span>
                <span className="statement-stat-value mono">{mostCommonCategory}</span>
              </div>
            </div>

            <div className="statement-divider" />

            <p className="statement-board">BOARD OF DIRECTORS: <span className="text-gold">YOU</span></p>

            <Button variant="secondary" size="sm" onClick={handleCopyStatement}>
              {copied ? 'Copied!' : 'Copy to Clipboard'}
            </Button>
          </div>
        </Card>
      </section>

      {/* CEO Comparison */}
      <section className="ceo-comparison-section">
        <Card elevated className="ceo-card">
          <h3 className="ceo-title">EXECUTIVE COMPARISON REPORT</h3>
          <p className="ceo-subtitle text-gray">Bathroom break earnings analysis</p>

          <div className="ceo-comparison-body">
            <div className="ceo-row">
              <span className="ceo-label">While you earned</span>
              <span className="ceo-value text-green mono">{formatCurrency(lifetimeEarned)}</span>
              <span className="ceo-context text-gray">in the bathroom...</span>
            </div>

            <div className="ceo-vs">VS</div>

            <div className="ceo-row">
              <span className="ceo-label">A Fortune 500 CEO earned</span>
              <span className="ceo-value text-gold mono">{formatCurrency(ceoEarnings)}</span>
              <span className="ceo-context text-gray">in the same amount of time</span>
            </div>
          </div>

          {lifetimeEarned > 0 && (
            <div className="ceo-multiplier">
              <span className="ceo-multiplier-value mono text-red">{multiplier}x</span>
              <span className="ceo-multiplier-label text-gray">CEO earnings multiplier</span>
            </div>
          )}

          <p className="ceo-footnote text-gray">
            Based on average Fortune 500 CEO compensation of ~$5,000/hour (~$83.33/min)
          </p>
        </Card>
      </section>
    </PageTransition>
  );
}
