import 'package:intl/intl.dart';

import '../../core/format/duration_formatter.dart';

/// Average Fortune 500 CEO compensation, per working minute. React constant.
const double ceoRatePerMinute = 83.33;

/// What a CEO earns over the same [totalDurationMs] the user spent on break.
double ceoEarningsFor(num totalDurationMs) =>
    (totalDurationMs / 60000) * ceoRatePerMinute;

/// The `Nx` figure, rounded to a whole number. Zero when nothing was earned,
/// matching React's guard against dividing by zero.
String ceoMultiplier({
  required double ceoEarnings,
  required double lifetimeEarned,
}) => lifetimeEarned > 0
    ? (ceoEarnings / lifetimeEarned).toStringAsFixed(0)
    : '0';

final DateFormat _statementDate = DateFormat('MMMM d, y', 'en_US');

/// `July 28, 2026`, matching the React `toLocaleDateString` options.
String statementDate(DateTime date) => _statementDate.format(date);

/// The exact ASCII payload copied to the clipboard. Byte-for-byte parity with
/// `handleCopyStatement` in `src/pages/Achievements.jsx`.
String buildEarningsStatement({
  required double lifetimeEarned,
  required int totalSessions,
  required int totalDurationMs,
  required num avgDurationMs,
  required String mostCommonCategory,
  required int unlockedCount,
  required int totalAchievements,
  required DateTime date,
  required String Function(num) formatMoney,
}) => <String>[
  '========================================',
  '   OFFICIAL EARNINGS STATEMENT',
  '   FuckCorpo Inc.',
  '   Date: ${statementDate(date)}',
  '========================================',
  '',
  '   Lifetime Earnings: ${formatMoney(lifetimeEarned)}',
  '   Total Sessions: $totalSessions',
  '   Total Time Invested: ${formatDuration(totalDurationMs)}',
  '   Average Session: ${formatDuration(avgDurationMs)}',
  '   Primary Category: $mostCommonCategory',
  '   Achievements Unlocked: $unlockedCount/$totalAchievements',
  '',
  '   BOARD OF DIRECTORS: YOU',
  '',
  '   --- CONFIDENTIAL ---',
  '   Generated by FuckCorpo Inc.',
  '========================================',
].join('\n');
